/**
 * S1→S3 capture step definitions.
 *
 * Each step describes which message to type in WebChat,
 * how long to record (ms), and which scene id it maps to.
 *
 * These steps are consumed by scripts/capture-scene.ts and
 * scripts/capture-all.ts.
 */

export interface CaptureStep {
  /** Must match a SceneAsset.id in src/scenes.ts */
  sceneId: string;
  /** Human-readable label for logging */
  label: string;
  /**
   * Chat message to type before starting the recording.
   * null = no new message (scene continues from previous state).
   */
  chatMessage: string | null;
  /** How many milliseconds to record this scene */
  recordMs: number;
  /**
   * Optional delay before starting the recording after the message is sent.
   * Allows the UI to settle (e.g., streaming reply completes).
   */
  delayBeforeRecordMs?: number;
  /** Whether this step requires the broken-build fixture to be loaded first */
  requiresBrokenBuild?: boolean;
}

/**
 * Deterministic broken-build fixture.
 * CPU socket AM5, Mainboard socket LGA1700 → E001 SOCKET_MISMATCH.
 */
export const BROKEN_BUILD_FIXTURE = {
  cpu: "AMD Ryzen 5 7600X",      // AM5
  motherboard: "MSI PRO Z790-P", // LGA1700
  description: "Socket mismatch: AM5 CPU + LGA1700 board",
};

export const CAPTURE_STEPS: CaptureStep[] = [
  {
    sceneId: "intro",
    label: "Intro title card — no capture needed (generated by Remotion)",
    chatMessage: null,
    recordMs: 0, // intro is a Remotion-generated scene, no WebChat capture
  },
  {
    sceneId: "search",
    label: "User requests gaming PC 25M VND",
    chatMessage:
      "Tôi cần build PC gaming ngân sách 25 triệu, chơi game AAA 1080p high settings",
    recordMs: 15000,
    delayBeforeRecordMs: 1000,
  },
  {
    sceneId: "compile",
    label: "Build Compiler returns valid build",
    chatMessage: null, // agent is still responding from previous step
    recordMs: 15000,
    delayBeforeRecordMs: 2000,
  },
  {
    sceneId: "broken-build",
    label: "User selects incompatible build",
    chatMessage:
      "Tôi muốn dùng AMD Ryzen 5 7600X với mainboard MSI PRO Z790-P, giá rẻ hơn",
    recordMs: 10000,
    delayBeforeRecordMs: 500,
    requiresBrokenBuild: true,
  },
  {
    sceneId: "detect-errors",
    label: "System detects E001 SOCKET_MISMATCH",
    chatMessage: null,
    recordMs: 15000,
    delayBeforeRecordMs: 2000,
  },
  {
    sceneId: "repair",
    label: "Repair workflow produces corrected build",
    chatMessage: "Sửa lỗi cho tôi đi",
    recordMs: 15000,
    delayBeforeRecordMs: 1000,
  },
  {
    sceneId: "auto-add",
    label: "Corrected components added to cart",
    chatMessage: null,
    recordMs: 10000,
    delayBeforeRecordMs: 2000,
  },
];

/** All capture steps excluding intro (which is Remotion-generated) */
export const WEBCHAT_CAPTURE_STEPS = CAPTURE_STEPS.filter(
  (s) => s.recordMs > 0
);
