import { CatalogComponent } from "./types.js";

export const MOCK_CATALOG: CatalogComponent[] = [
  // CPU - AM5 (6 CPUs: 3 in-stock, 3 out-of-stock)
  {
    id: "cpu-001",
    name: "AMD Ryzen 7 7800X3D",
    type: "cpu",
    price: 9500000,
    stock_status: "in_stock",
    promo: null,
    socket: "AM5",
    tdp: 120,
    ram_gen_supported: ["DDR5"],
  },
  {
    id: "cpu-002",
    name: "AMD Ryzen 9 7950X",
    type: "cpu",
    price: 12000000,
    stock_status: "in_stock",
    promo: null,
    socket: "AM5",
    tdp: 170,
    ram_gen_supported: ["DDR5"],
  },
  {
    id: "cpu-003",
    name: "AMD Ryzen 5 7600",
    type: "cpu",
    price: 4500000,
    stock_status: "in_stock",
    promo: "Giảm 500K",
    socket: "AM5",
    tdp: 65,
    ram_gen_supported: ["DDR5"],
  },
  {
    id: "cpu-004",
    name: "AMD Ryzen 7 9700X",
    type: "cpu",
    price: 11000000,
    stock_status: "out_of_stock",
    promo: null,
    socket: "AM5",
    tdp: 105,
    ram_gen_supported: ["DDR5"],
  },
  {
    id: "cpu-005",
    name: "AMD Ryzen 5 7600X",
    type: "cpu",
    price: 5500000,
    stock_status: "out_of_stock",
    promo: null,
    socket: "AM5",
    tdp: 105,
    ram_gen_supported: ["DDR5"],
  },
  {
    id: "cpu-006",
    name: "Intel Core i9-14900K",
    type: "cpu",
    price: 14000000,
    stock_status: "out_of_stock",
    promo: null,
    socket: "LGA1700",
    tdp: 150,
    ram_gen_supported: ["DDR5"],
  },

  // Mainboard - AM5 & LGA1700 (6 mainboards)
  {
    id: "mb-001",
    name: "ASUS TUF B650-PLUS",
    type: "mainboard",
    price: 3200000,
    stock_status: "in_stock",
    promo: null,
    socket: "AM5",
    ram_gen_supported: ["DDR5"],
    form_factor: "ATX",
  },
  {
    id: "mb-002",
    name: "MSI B650E Gaming WiFi",
    type: "mainboard",
    price: 3800000,
    stock_status: "in_stock",
    promo: "Tặng kabel",
    socket: "AM5",
    ram_gen_supported: ["DDR5"],
    form_factor: "ATX",
  },
  {
    id: "mb-003",
    name: "ASUS ROG STRIX X870-F",
    type: "mainboard",
    price: 5000000,
    stock_status: "in_stock",
    promo: null,
    socket: "AM5",
    ram_gen_supported: ["DDR5"],
    form_factor: "ATX",
  },
  {
    id: "mb-004",
    name: "MSI MPG B750E Edge WiFi",
    type: "mainboard",
    price: 4200000,
    stock_status: "out_of_stock",
    promo: null,
    socket: "AM5",
    ram_gen_supported: ["DDR5"],
    form_factor: "mATX",
  },
  {
    id: "mb-005",
    name: "GIGABYTE B650 AORUS Master",
    type: "mainboard",
    price: 4500000,
    stock_status: "out_of_stock",
    promo: null,
    socket: "AM5",
    ram_gen_supported: ["DDR5"],
    form_factor: "ATX",
  },
  {
    id: "mb-006",
    name: "ASUS ProArt B760-Creator",
    type: "mainboard",
    price: 5500000,
    stock_status: "out_of_stock",
    promo: null,
    socket: "LGA1700",
    ram_gen_supported: ["DDR5"],
    form_factor: "ATX",
  },

  // RAM - DDR5 & DDR4 (6 RAM modules)
  {
    id: "ram-001",
    name: "Corsair Vengeance DDR5 32GB (2x16GB) 6000MHz",
    type: "ram",
    price: 2800000,
    stock_status: "in_stock",
    promo: null,
    generation: "DDR5",
    tdp: 3,
  },
  {
    id: "ram-002",
    name: "Kingston FURY Beast DDR5 32GB (2x16GB) 5600MHz",
    type: "ram",
    price: 2500000,
    stock_status: "in_stock",
    promo: "Giảm 200K",
    generation: "DDR5",
    tdp: 3,
  },
  {
    id: "ram-003",
    name: "G.Skill Trident Z5 DDR5 64GB (2x32GB) 6400MHz",
    type: "ram",
    price: 5000000,
    stock_status: "in_stock",
    promo: null,
    generation: "DDR5",
    tdp: 3,
  },
  {
    id: "ram-004",
    name: "Corsair Vengeance DDR4 32GB (2x16GB) 3200MHz",
    type: "ram",
    price: 2000000,
    stock_status: "out_of_stock",
    promo: null,
    generation: "DDR4",
    tdp: 2,
  },
  {
    id: "ram-005",
    name: "Kingston HyperX DDR4 16GB (2x8GB) 3200MHz",
    type: "ram",
    price: 1200000,
    stock_status: "out_of_stock",
    promo: null,
    generation: "DDR4",
    tdp: 2,
  },
  {
    id: "ram-006",
    name: "G.Skill Ripjaws DDR4 32GB (2x16GB) 3600MHz",
    type: "ram",
    price: 2300000,
    stock_status: "out_of_stock",
    promo: null,
    generation: "DDR4",
    tdp: 2,
  },

  // PSU - 550W-1000W (6 PSUs)
  {
    id: "psu-001",
    name: "Corsair RM650",
    type: "psu",
    price: 1800000,
    stock_status: "in_stock",
    promo: null,
    wattage: 650,
    form_factor: "ATX",
  },
  {
    id: "psu-002",
    name: "EVGA SuperNOVA 750 G6",
    type: "psu",
    price: 2200000,
    stock_status: "in_stock",
    promo: "Tặng kabel",
    wattage: 750,
    form_factor: "ATX",
  },
  {
    id: "psu-003",
    name: "Seasonic FOCUS Plus 850",
    type: "psu",
    price: 2600000,
    stock_status: "in_stock",
    promo: null,
    wattage: 850,
    form_factor: "ATX",
  },
  {
    id: "psu-004",
    name: "Corsair SF750",
    type: "psu",
    price: 2400000,
    stock_status: "out_of_stock",
    promo: null,
    wattage: 750,
    form_factor: "SFX",
  },
  {
    id: "psu-005",
    name: "MSI A650 GOLD 650W",
    type: "psu",
    price: 1900000,
    stock_status: "out_of_stock",
    promo: null,
    wattage: 650,
    form_factor: "ATX",
  },
  {
    id: "psu-006",
    name: "be quiet! Pure Power 1000W",
    type: "psu",
    price: 3200000,
    stock_status: "out_of_stock",
    promo: null,
    wattage: 1000,
    form_factor: "ATX",
  },

  // Cooler - Air & AIO (6 coolers)
  {
    id: "cooler-001",
    name: "Noctua NH-D15",
    type: "cooler",
    price: 900000,
    stock_status: "in_stock",
    promo: null,
    socket: ["AM5", "AM4", "LGA1700"],
    height: 160,
    tdp: 250,
  },
  {
    id: "cooler-002",
    name: "Corsair H150i Elite Capellix",
    type: "cooler",
    price: 2200000,
    stock_status: "in_stock",
    promo: "Giảm RGB",
    socket: ["AM5", "LGA1700"],
    height: 120,
    tdp: 280,
  },
  {
    id: "cooler-003",
    name: "Noctua NH-U12S chromax",
    type: "cooler",
    price: 700000,
    stock_status: "in_stock",
    promo: null,
    socket: ["AM5", "AM4", "LGA1700"],
    height: 155,
    tdp: 220,
  },
  {
    id: "cooler-004",
    name: "Lian Li Galahad AIO 360",
    type: "cooler",
    price: 1800000,
    stock_status: "out_of_stock",
    promo: null,
    socket: ["AM5", "LGA1700"],
    height: 120,
    tdp: 260,
  },
  {
    id: "cooler-005",
    name: "Thermalright Peerless Assassin 120 SE",
    type: "cooler",
    price: 600000,
    stock_status: "out_of_stock",
    promo: null,
    socket: ["AM5", "LGA1700"],
    height: 165,
    tdp: 280,
  },
  {
    id: "cooler-006",
    name: "Arctic Liquid Freezer II 240",
    type: "cooler",
    price: 1500000,
    stock_status: "out_of_stock",
    promo: null,
    socket: ["AM5", "LGA1700"],
    height: 120,
    tdp: 240,
  },

  // Case - ATX, mATX, ITX (6 cases)
  {
    id: "case-001",
    name: "Corsair 5000T RGB",
    type: "case",
    price: 3500000,
    stock_status: "in_stock",
    promo: null,
    form_factor: "ATX",
    max_cooler_height: 170,
    supported_mb_form_factors: ["ATX", "mATX", "ITX"],
    supported_psu_form_factors: ["ATX", "SFX"],
    clearance_mm: 370,
  },
  {
    id: "case-002",
    name: "Lian Li Lancool 216",
    type: "case",
    price: 1200000,
    stock_status: "in_stock",
    promo: "Giảm quạt",
    form_factor: "ATX",
    max_cooler_height: 160,
    supported_mb_form_factors: ["ATX", "mATX", "ITX"],
    supported_psu_form_factors: ["ATX", "SFX"],
    clearance_mm: 320,
  },
  {
    id: "case-003",
    name: "Fractal Core 1000",
    type: "case",
    price: 900000,
    stock_status: "in_stock",
    promo: null,
    form_factor: "mATX",
    max_cooler_height: 160,
    supported_mb_form_factors: ["mATX", "ITX"],
    supported_psu_form_factors: ["ATX", "SFX"],
    clearance_mm: 280,
  },
  {
    id: "case-004",
    name: "Noctua D5 XL",
    type: "case",
    price: 800000,
    stock_status: "out_of_stock",
    promo: null,
    form_factor: "mATX",
    max_cooler_height: 165,
    supported_mb_form_factors: ["mATX", "ITX"],
    supported_psu_form_factors: ["SFX"],
    clearance_mm: 250,
  },
  {
    id: "case-005",
    name: "Sliger SM580",
    type: "case",
    price: 1800000,
    stock_status: "out_of_stock",
    promo: null,
    form_factor: "ITX",
    max_cooler_height: 85,
    supported_mb_form_factors: ["ITX"],
    supported_psu_form_factors: ["SFX"],
    clearance_mm: 200,
  },
  {
    id: "case-006",
    name: "Jonsbo RM4",
    type: "case",
    price: 1600000,
    stock_status: "out_of_stock",
    promo: null,
    form_factor: "ITX",
    max_cooler_height: 80,
    supported_mb_form_factors: ["ITX"],
    supported_psu_form_factors: ["SFX"],
    clearance_mm: 180,
  },

  // Storage - NVMe, SATA SSD, HDD (6 storage devices)
  {
    id: "storage-001",
    name: "Samsung 980 Pro 1TB NVMe SSD",
    type: "storage",
    price: 1200000,
    stock_status: "in_stock",
    promo: null,
  },
  {
    id: "storage-002",
    name: "WD Black SN850X 1TB NVMe SSD",
    type: "storage",
    price: 1100000,
    stock_status: "in_stock",
    promo: "Giảm 100K",
    height: undefined,
  },
  {
    id: "storage-003",
    name: "Crucial P5 Plus 1TB NVMe SSD",
    type: "storage",
    price: 1000000,
    stock_status: "in_stock",
    promo: null,
  },
  {
    id: "storage-004",
    name: "Samsung 870 QVO 1TB SATA SSD",
    type: "storage",
    price: 700000,
    stock_status: "out_of_stock",
    promo: null,
  },
  {
    id: "storage-005",
    name: "Seagate Barracuda 2TB HDD",
    type: "storage",
    price: 800000,
    stock_status: "out_of_stock",
    promo: null,
  },
  {
    id: "storage-006",
    name: "WD Red Plus 2TB HDD",
    type: "storage",
    price: 1000000,
    stock_status: "out_of_stock",
    promo: null,
  },

  // GPU - NVIDIA & AMD (8 GPUs)
  {
    id: "gpu-001",
    name: "NVIDIA RTX 4090",
    type: "gpu",
    price: 35000000,
    stock_status: "in_stock",
    promo: null,
    tdp: 450,
    clearance_mm: 320,
  },
  {
    id: "gpu-002",
    name: "NVIDIA RTX 4080",
    type: "gpu",
    price: 22000000,
    stock_status: "in_stock",
    promo: "Giảm 1M",
    tdp: 320,
    clearance_mm: 310,
  },
  {
    id: "gpu-003",
    name: "NVIDIA RTX 4070",
    type: "gpu",
    price: 12000000,
    stock_status: "in_stock",
    promo: null,
    tdp: 200,
    clearance_mm: 280,
  },
  {
    id: "gpu-004",
    name: "AMD Radeon RX 7900 XTX",
    type: "gpu",
    price: 18000000,
    stock_status: "in_stock",
    promo: null,
    tdp: 420,
    clearance_mm: 330,
  },
  {
    id: "gpu-005",
    name: "NVIDIA RTX 4070 Super",
    type: "gpu",
    price: 13500000,
    stock_status: "out_of_stock",
    promo: null,
    tdp: 220,
    clearance_mm: 290,
  },
  {
    id: "gpu-006",
    name: "AMD Radeon RX 7800 XT",
    type: "gpu",
    price: 11000000,
    stock_status: "out_of_stock",
    promo: null,
    tdp: 310,
    clearance_mm: 270,
  },
  {
    id: "gpu-007",
    name: "Intel Arc A770",
    type: "gpu",
    price: 7000000,
    stock_status: "out_of_stock",
    promo: null,
    tdp: 225,
    clearance_mm: 250,
  },
  {
    id: "gpu-008",
    name: "NVIDIA RTX 4060",
    type: "gpu",
    price: 5500000,
    stock_status: "out_of_stock",
    promo: null,
    tdp: 115,
    clearance_mm: 200,
  },
];
