(function () {
  if (!globalThis.BuildMateEligibility.isExactBuildPcUrl(location.href)) return;
  const panel = globalThis.BuildMatePanel.ensureMounted(); let actionController = null;
  const trackerStop = globalThis.BuildMateTracker.startBuildTracker({ doc: document, onSnapshot: (snapshot) => panel.setSnapshot(snapshot) });
  const bridge = globalThis.BuildMateBridgeAdapter.createBridgeAdapter({ onCommand: (command) => panel.applyBridgeCommand(command) });
  async function runDemoAdd() { if (actionController || !globalThis.BuildMateEligibility.isExactBuildPcUrl(location.href)) return; actionController = new AbortController(); panel.setAction({ type: "START" }); const result = await globalThis.BuildMatePageActions.addFirstVga({ signal: actionController.signal, onStep: (status, message) => panel.setAction({ type: "STEP", status, message }) }); actionController = null; if (result.code === "CANCELLED") panel.setAction({ type: "CANCEL" }); else if (!result.ok) { const detail = JSON.stringify(globalThis.BuildMatePageActions.diagnostics(document)); console.info("[BuildMate DOM demo] action failed", result.code, detail); panel.setAction({ type: "FAILED", code: result.code, message: `${result.message} (DOM: ${detail})` }); } else if (result.unverified) panel.setAction({ type: "UNVERIFIED", message: result.message }); else panel.setAction({ type: "SUCCESS", message: result.message }); }
  panel.setHandlers({ onRequestAdd: runDemoAdd, onCancelAction: () => actionController?.abort(), onMockCommand: () => bridge.receive({ v: 1, id: `mock-${Date.now()}`, type: "buildmate.ui.suggest", tab: { origin: "https://phongvu.vn", path: "/buildpc" }, issuedAt: Date.now(), expiresAt: Date.now() + 30000, payload: { message: "OpenClaw mock: hãy xác nhận trước khi thêm VGA demo.", category: "VGA" } }) });
  chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => { if (!globalThis.BuildMateEligibility.isExactBuildPcUrl(location.href)) return undefined; if (message?.type === "BUILDMATE_TOGGLE_PANEL") { sendResponse({ ok: true, open: panel.toggle().open }); return undefined; } if (message?.type === "BUILDMATE_MOCK_NODE_COMMAND") { sendResponse(bridge.receive(message.command)); return undefined; } return undefined; });
  addEventListener("pagehide", () => { actionController?.abort(); trackerStop(); }, { once: true });
})();
