(function () {
  const ROOT_ID = "buildmate-extension-root";
  function escapeHtml(value) { return String(value ?? "").replace(/[&<>'"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[c]); }
  function ensureMounted() {
    const existing = document.getElementById(ROOT_ID); if (existing?.__buildMatePanel) return existing.__buildMatePanel;
    const host = document.createElement("div"); host.id = ROOT_ID; host.setAttribute("data-buildmate-owner", "extension"); const shadow = host.attachShadow({ mode: "open" });
    shadow.innerHTML = `<link rel="stylesheet" href="${chrome.runtime.getURL("panel.css")}"><button class="bm-launcher" type="button" aria-expanded="false" aria-controls="bm-panel"><span aria-hidden="true">✦</span> BuildMate</button><aside id="bm-panel" class="bm-panel" data-open="false" aria-label="Trợ lý BuildMate"><div class="bm-topline"><div class="bm-brand"><span class="bm-brand-dot"></span> BuildMate</div><button class="bm-close" type="button" aria-label="Đóng BuildMate">Đóng</button></div><div class="bm-panel-header"><h2 class="bm-title" tabindex="-1">Trợ lý build PC</h2></div><p class="bm-notice"></p><div class="bm-view"></div></aside>`;
    document.documentElement.appendChild(host);
    const launcher = shadow.querySelector(".bm-launcher"), panel = shadow.querySelector(".bm-panel"), notice = shadow.querySelector(".bm-notice"), view = shadow.querySelector(".bm-view"), title = shadow.querySelector(".bm-title");
    let state = { ...globalThis.BuildMatePanelState.initialPanelState }, actionState = { ...globalThis.BuildMateActionState.initialActionState }, snapshot = { status: "unavailable", components: [], total: null }, pendingAdd = false, bridgeMessage = "Gateway relay chưa kết nối — đang chạy demo local.", handlers = {};
    function snapshotMarkup() { if (snapshot.status !== "ready") return `<div class="bm-tracker bm-tracker--unavailable">Không đọc được build hiện tại. Bạn có thể refresh trang rồi thử lại.</div>`; const names = snapshot.components.length ? snapshot.components.map((c) => `<li><span>${escapeHtml(c.category)}</span>${escapeHtml(c.name)}</li>`).join("") : "<li>Chưa thấy linh kiện đã chọn.</li>"; return `<section class="bm-tracker"><div class="bm-tracker-title">Build đang thấy trên trang</div><ul>${names}</ul>${snapshot.total ? `<strong>${escapeHtml(snapshot.total)}</strong>` : ""}</section>`; }
    function actionMarkup() { if (pendingAdd) return `<div class="bm-confirm"><strong>Xác nhận thêm VGA demo?</strong><p>Extension chỉ mở category VGA và chọn product đầu tiên hiển thị. Không checkout hoặc điều hướng.</p><div><button class="bm-primary" type="button" data-action="confirm-add">Xác nhận thêm VGA</button><button class="bm-back" type="button" data-action="cancel-add">Huỷ</button></div></div>`; if (actionState.status === "idle") return `<button class="bm-primary" type="button" data-action="prepare-add">Thêm VGA demo</button>`; const busy = globalThis.BuildMateActionState.activeStatuses.has(actionState.status); return `<div class="bm-action-status ${busy ? "bm-action-status--busy" : ""}" role="status" aria-live="polite"><strong>${escapeHtml(actionState.message)}</strong>${actionState.errorCode ? `<span>${escapeHtml(actionState.errorCode)}</span>` : ""}${busy ? '<button class="bm-back" type="button" data-action="cancel-running">Huỷ thao tác</button>' : '<button class="bm-back" type="button" data-action="reset-action">Demo mới</button>'}</div>`; }
    function viewMarkup() { const { DEMO_NOTICE, goals } = globalThis.BuildMateDemoData; const selected = goals.find((goal) => goal.id === state.selectedGoalId); const goalMarkup = state.activeView === "goal" && selected ? `<div class="bm-summary"><div class="bm-summary-label">Mục tiêu mẫu</div><div class="bm-summary-value">${escapeHtml(selected.title)}</div></div><p class="bm-copy">${escapeHtml(selected.summary)}</p><button class="bm-back" type="button" data-action="welcome">Chọn mục tiêu khác</button>` : `<p class="bm-copy">Chatbot đang theo dõi Build PC read-only. Chọn mục tiêu mẫu hoặc thử flow VGA dưới đây.</p><div class="bm-goals">${goals.map((goal) => `<button class="bm-goal" type="button" data-goal-id="${escapeHtml(goal.id)}"><strong>${escapeHtml(goal.title)}</strong><span>${escapeHtml(goal.budget)}</span></button>`).join("")}</div>`; return `<p class="bm-notice-copy">${escapeHtml(DEMO_NOTICE)}</p><p class="bm-bridge">${escapeHtml(bridgeMessage)}</p>${goalMarkup}${snapshotMarkup()}${actionMarkup()}<button class="bm-link" type="button" data-action="mock-suggest">Mô phỏng gợi ý từ OpenClaw</button>`; }
    function render({ focusPanel = false } = {}) { panel.dataset.open = String(state.open); launcher.setAttribute("aria-expanded", String(state.open)); notice.textContent = "Chatbot demo: build snapshot là read-only; mọi thao tác thêm sản phẩm cần xác nhận."; view.innerHTML = viewMarkup(); if (focusPanel && state.open) title.focus(); }
    function transition(event, options) { const wasOpen = state.open; state = globalThis.BuildMatePanelState.reducePanelState(state, event); render({ focusPanel: options?.focusPanel ?? (!wasOpen && state.open) }); if (wasOpen && !state.open) launcher.focus(); return state; }
    launcher.addEventListener("click", () => transition({ type: "TOGGLE" })); shadow.querySelector(".bm-close").addEventListener("click", () => transition({ type: "CLOSE" }));
    panel.addEventListener("click", (event) => { const button = event.target.closest("button"); if (!button) return; if (button.dataset.goalId) transition({ type: "SELECT_GOAL", goalId: button.dataset.goalId }); if (button.dataset.action === "welcome") transition({ type: "SHOW_WELCOME" }); if (button.dataset.action === "prepare-add") { pendingAdd = true; render(); } if (button.dataset.action === "cancel-add") { pendingAdd = false; render(); } if (button.dataset.action === "confirm-add") { pendingAdd = false; handlers.onRequestAdd?.(); render(); } if (button.dataset.action === "cancel-running") handlers.onCancelAction?.(); if (button.dataset.action === "reset-action") { actionState = { ...globalThis.BuildMateActionState.initialActionState }; render(); } if (button.dataset.action === "mock-suggest") handlers.onMockCommand?.(); });
    shadow.addEventListener("keydown", (event) => { if (event.key === "Escape" && state.open) { event.preventDefault(); transition({ type: "CLOSE" }); } });
    const api = { toggle: () => transition({ type: "TOGGLE" }), setHandlers: (next) => { handlers = next; }, setAction: (event) => { actionState = globalThis.BuildMateActionState.reduceActionState(actionState, event); render(); }, setSnapshot: (next) => { snapshot = next; render(); }, applyBridgeCommand: (command) => { bridgeMessage = command.payload.message; if (command.type === "buildmate.build.request-add") pendingAdd = true; render(); } };
    host.__buildMatePanel = api; render(); return api;
  }
  globalThis.BuildMatePanel = { ensureMounted };
})();
